blank_issues_enabled: false
contact_links:
  - name: Sponsorship and partnerships
    url: mailto:rizal.alfariiiziii@gmail.com
    about: Contact Alfarizi if you want to sponsor this project or discuss partnership opportunities.
